#!/bin/sh
#
# install-nano-pilot.sh — drop a HeliosDB-Nano pilot into the
# current git repo. Idempotent: re-run safely.
#
# What it sets up:
#   .helios-nano/                       — root data directory
#   .helios-nano/bin/heliosdb-nano      — the binary (built from source
#                                         when no release is available)
#   .helios-nano/data/                  — RocksDB data files
#   .helios-nano/config.toml            — defaults (loopback, no auth)
#   .git/hooks/pre-commit               — runs the code-graph hook
#   .gitignore                          — excludes .helios-nano/
#
# Usage (from any git repo root):
#   sh scripts/install-nano-pilot.sh
#
# Or pipe from the canonical raw URL:
#   curl -fsSL <raw-url>/scripts/install-nano-pilot.sh | sh

set -eu

# ── locate repo root ────────────────────────────────────────────────────
if ! REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  echo "fatal: run this from inside a git repository" >&2
  exit 1
fi
HELIOS_DIR="$REPO_ROOT/.helios-nano"
BIN_DIR="$HELIOS_DIR/bin"
DATA_DIR="$HELIOS_DIR/data"
CONFIG="$HELIOS_DIR/config.toml"

mkdir -p "$BIN_DIR" "$DATA_DIR"

# ── locate or build the binary ──────────────────────────────────────────
BIN="$BIN_DIR/heliosdb-nano"
if [ ! -x "$BIN" ]; then
  echo "==> building heliosdb-nano with the code-graph + mcp-endpoint feature set"
  if ! command -v cargo >/dev/null 2>&1; then
    echo "fatal: cargo not on PATH; install Rust first" >&2
    exit 1
  fi
  ( cd "$REPO_ROOT" && \
    cargo build --release --features code-graph,graph-rag,mcp-endpoint )
  cp "$REPO_ROOT/target/release/heliosdb-nano" "$BIN"
fi

# ── default config ──────────────────────────────────────────────────────
if [ ! -f "$CONFIG" ]; then
  cat > "$CONFIG" <<EOF
# HeliosDB-Nano pilot config — adjust as needed.

[storage]
data_dir = "$DATA_DIR"

[code_graph]
auto_reparse = true
default_source_table = "src"

[mcp]
bind = "127.0.0.1:0"   # loopback only by default; set non-zero port to expose
auth = "disabled"       # use jwt_secret for non-loopback binds; bind_safety_check enforces this
EOF
fi

# ── .gitignore ──────────────────────────────────────────────────────────
GITIGNORE="$REPO_ROOT/.gitignore"
if ! grep -q "^.helios-nano/" "$GITIGNORE" 2>/dev/null; then
  echo ".helios-nano/" >> "$GITIGNORE"
  echo "==> added .helios-nano/ to .gitignore"
fi

# ── pre-commit hook ─────────────────────────────────────────────────────
HOOK="$REPO_ROOT/.git/hooks/pre-commit"
if [ ! -f "$HOOK" ] || ! grep -q "heliosdb-nano code-graph hook" "$HOOK"; then
  cat > "$HOOK" <<EOF
#!/bin/sh
# Auto-generated by install-nano-pilot.sh: keep the code-graph
# index in sync with each commit.
HELIOS_DIR="\$(git rev-parse --show-toplevel)/.helios-nano"
if [ -x "\$HELIOS_DIR/bin/heliosdb-nano" ]; then
  git diff --cached --name-only --diff-filter=ACMR | \\
    "\$HELIOS_DIR/bin/heliosdb-nano" code-graph hook \\
      --data-dir "\$HELIOS_DIR/data" \\
      --repo-root "\$(git rev-parse --show-toplevel)" \\
      --source-table src 2>/dev/null || true
fi
EOF
  chmod +x "$HOOK"
  echo "==> installed .git/hooks/pre-commit"
fi

# ── final pointer ───────────────────────────────────────────────────────
cat <<EOF

==============================================================
HeliosDB-Nano pilot installed at $HELIOS_DIR

Cold-index this repo's source tree:
  $BIN code-graph index --data-dir $DATA_DIR --table src

Wire into Claude Code (~/.config/claude/claude.json):
{
  "mcpServers": {
    "helios-nano-$(basename "$REPO_ROOT")": {
      "command": "$BIN",
      "args": ["mcp-server", "--db", "$DATA_DIR"]
    }
  }
}

Tear down with:  rm -rf $HELIOS_DIR
==============================================================
EOF
